# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-29 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='x4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='x2',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
