# Generated by Django 4.1.1 on 2022-09-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campo',
            new_name='campos',
        ),
    ]
